options:
  hhvm-mirror:
    default: 'http://dl.hhvm.com/ubuntu'
    description: |
      Default mirror for downloading HHVM. You can find other mirrors at
      https://github.com/facebook/hhvm/wiki/Mirror
    type: string
